# Generated by Django 5.2.6 on 2025-09-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('name', models.TextField()),
                ('code', models.CharField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
