# Generated by Django 5.2.6 on 2025-09-19 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('name', models.CharField(primary_key=True, serialize=False)),
                ('manufacturer', models.CharField()),
                ('takeoff_req', models.IntegerField()),
                ('landing_req', models.IntegerField()),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('code', models.CharField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='airport',
            name='domestic',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ATC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.FloatField()),
                ('active', models.BooleanField(default=True)),
                ('number', models.IntegerField(default=1)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airport.airport')),
            ],
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id',models.AutoField(auto_created=True, primary_key=True, serialize=False,verbose_name='ID')),
                ('code', models.CharField()),
                ('active', models.BooleanField(default=True)),
                ('capacity', models.IntegerField()),
                ('domestic', models.BooleanField(default=True)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airport.airport')),
            ],
        ),
    ]
