# Generated by Django 5.2.6 on 2025-09-20 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0002_aircraft_airline_airport_domestic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirportEntity',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('code', models.CharField()),
                ('capacity', models.IntegerField()),
                ('free_at', models.DateTimeField()),
                ('entity', models.CharField(choices=[('BG', 'BAGGAGE_BELT'), ('GT', 'GATE')])),
            ],
        ),
        migrations.CreateModel(
            name='Runway',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('length', models.IntegerField()),
                ('material', models.CharField()),
                ('free_at', models.DateTimeField()),
                ('number_1', models.CharField()),
                ('number_2', models.CharField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='terminal',
            name='pk',
        ),
        migrations.AddField(
            model_name='terminal',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddConstraint(
            model_name='terminal',
            constraint=models.UniqueConstraint(fields=('code', 'airport'), name='unique_terminal'),
        ),
        migrations.AddField(
            model_name='airportentity',
            name='terminal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airport.terminal'),
        ),
        migrations.AddField(
            model_name='runway',
            name='airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airport.airport'),
        ),
        migrations.AddConstraint(
            model_name='airportentity',
            constraint=models.UniqueConstraint(fields=('terminal', 'code'), name='unique_entity'),
        ),
        migrations.AddConstraint(
            model_name='runway',
            constraint=models.UniqueConstraint(fields=('airport', 'number_1', 'number_2'), name='unique_runway'),
        ),
    ]
