# Generated by Django 5.2.6 on 2025-09-20 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0003_airportentity_runway_remove_terminal_pk_terminal_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airportentity',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='runway',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
