# Generated by Django 5.2.6 on 2025-09-20 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0004_alter_airportentity_id_alter_runway_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airportentity',
            name='free_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='runway',
            name='free_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='AirlineAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airport.airline')),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airport.airport')),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('code', models.CharField(primary_key=True, serialize=False)),
                ('arrival_time', models.TimeField()),
                ('departure_time', models.TimeField()),
                ('domestic', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('Aircraft', models.ForeignKey(default='NA', on_delete=django.db.models.deletion.SET_DEFAULT, to='airport.aircraft')),
                ('airline', models.ForeignKey(default='NA', on_delete=django.db.models.deletion.SET_DEFAULT, to='airport.airline')),
                ('destination', models.ForeignKey(default='NA', on_delete=django.db.models.deletion.SET_DEFAULT, to='airport.airport')),
                ('source', models.ForeignKey(default='NA', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='source_aiport_code', to='airport.airport')),
            ],
        ),
        migrations.CreateModel(
            name='FlightInstance',
            fields=[
                ('id',models.AutoField(auto_created=True, primary_key=True, serialize=False,verbose_name='ID')),
                ('code', models.CharField(serialize=False)),
                ('arrival_time', models.DateTimeField()),
                ('departure_time', models.DateTimeField()),
                ('scheduled_arrival_time', models.DateTimeField()),
                ('scheduled_departure_time', models.DateTimeField()),
                ('domestic', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Aircraft', models.ForeignKey(default='NA', on_delete=django.db.models.deletion.SET_DEFAULT, to='airport.aircraft')),
                ('airline', models.ForeignKey(default='NA', on_delete=django.db.models.deletion.SET_DEFAULT, to='airport.airline')),
                ('baggage', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='airport.airportentity')),
                ('destination', models.ForeignKey(default='NA', on_delete=django.db.models.deletion.SET_DEFAULT, to='airport.airport')),
                ('gate', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='source_aiport_gate_code', to='airport.airportentity')),
                ('landing_runway', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='airport.runway')),
                ('source', models.ForeignKey(default='NA', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='source_aiport_code_instance', to='airport.airport')),
                ('take_off_runway', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='source_aiport_runway_code', to='airport.runway')),
            ],
        ),
        migrations.CreateModel(
            name='AirportEntityLogging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(choices=[('BG', 'BAGGAGE_BELT'), ('GT', 'GATE')])),
                ('assigned_time', models.DateTimeField()),
                ('valid_till', models.DateTimeField()),
                ('action', models.CharField(choices=[('A', 'ALLOTED'), ('C', 'CLOSED'), ('R', 'REVOKED')])),
                ('flight_instance', models.ForeignKey(default='NA', on_delete=django.db.models.deletion.SET_DEFAULT, to='airport.flightinstance')),
            ],
        ),
    ]
