# Generated by Django 5.2.6 on 2025-09-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0005_alter_airportentity_free_at_alter_runway_free_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightinstance',
            name='active',
        ),
        migrations.RemoveField(
            model_name='flightinstance',
            name='approved',
        ),
        migrations.AddField(
            model_name='airlineacceptance',
            name='state',
            field=models.CharField(choices=[('P', 'PENDING'), ('A', 'ACCEPTED'), ('R', 'REJECTED')], default='P'),
        ),
        migrations.AddField(
            model_name='flightinstance',
            name='state',
            field=models.CharField(choices=[('P', 'PENDING'), ('A', 'ACCEPTED'), ('R', 'REJECTED'), ('G', 'GATE'), ('PU', 'PUSHBACK'), ('TO', 'TAXIOUT'), ('T', 'TAKEOFF'), ('AI', 'AIR'), ('L', 'LANDING'), ('TI', 'TAXIIN'), ('B', 'BAGGAGE'), ('C', 'CLOSED')], default='P'),
        ),
    ]
