# Generated by Django 5.2.6 on 2025-09-22 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0006_remove_flightinstance_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightinstance',
            name='baggage',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='source_aiport_baggage_code', to='airport.airportentity'),
        ),
        migrations.AlterField(
            model_name='flightinstance',
            name='landing_runway',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='destination_aiport_runway_code', to='airport.runway'),
        ),
    ]
