# Generated by Django 5.2.6 on 2025-09-23 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0008_alter_flightinstance_baggage_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AirportEntityLogging',
        ),
    ]
