# Generated by Django 5.2.6 on 2025-09-23 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0009_delete_airportentitylogging'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='flightinstance',
        #     name='id',
        #     field=models.AutoField(primary_key=True, serialize=False),
        # ),
        # migrations.AlterField(
        #     model_name='flightinstance',
        #     name='code',
        #     field=models.CharField(),
        # ),
        migrations.CreateModel(
            name='AirportEntityLogging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(choices=[('BG', 'BAGGAGE_BELT'), ('GT', 'GATE')])),
                ('assigned_time', models.DateTimeField()),
                ('valid_till', models.DateTimeField()),
                ('action', models.CharField(choices=[('A', 'ALLOTED'), ('C', 'CLOSED'), ('R', 'REVOKED')])),
                ('flight_instance', models.ForeignKey(default='NA', on_delete=django.db.models.deletion.SET_DEFAULT, to='airport.flightinstance')),
            ],
        ),
    ]
