# Generated by Django 5.2.6 on 2025-09-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0010_flightinstance_id_alter_flightinstance_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airportentity',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
