# Generated by Django 5.2.6 on 2025-09-27 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0011_airportentity_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airportentity',
            name='terminal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airport_entity', to='airport.terminal'),
        ),
        migrations.AlterField(
            model_name='flightinstance',
            name='state',
            field=models.CharField(choices=[('P', 'PENDING'), ('A', 'ACCEPTED'), ('R', 'REJECTED'), ('G', 'GATE'), ('PU', 'PUSHBACK'), ('TO', 'TAXIOUT'), ('T', 'TAKEOFF'), ('AI', 'AIR'), ('L', 'LANDING'), ('TI', 'TAXIIN'), ('B', 'BAGGAGE'), ('C', 'CLOSED'), ('CA', 'CANCELLED'), ('DIV', 'DIVERTED'), ('AP', 'INAPPROACH')], default='P'),
        ),
        migrations.AlterField(
            model_name='runway',
            name='airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runways', to='airport.airport'),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminals', to='airport.airport'),
        ),
    ]
