# Generated by Django 5.2.6 on 2025-11-16 11:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0012_alter_airportentity_terminal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airportentity',
            name='flightId',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='airportentity',
            name='free_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='flightinstance',
            name='code',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='flightinstance',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='flightinstance',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='runway',
            name='free_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
